"""backend-api-master - OmniSkill search script.

Auto-generated by OmniSkill for the 'backend-api-master' skill.
Searches the knowledge base and outputs results in llms.txt format.
"""

from __future__ import annotations

from pathlib import Path

from omniskill.core.assembler import OutputFormat, PromptAssembler
from omniskill.core.engine import SearchEngine

DATASET_DIR = Path(__file__).parent / "datasets"


def create_engine() -> SearchEngine:
    """Create and index a SearchEngine from the dataset directory."""
    engine = SearchEngine()
    engine.index_directory(DATASET_DIR)
    return engine


def search(query: str, limit: int = 10) -> str:
    """Search the knowledge base and return llms.txt formatted context."""
    engine = create_engine()
    results = engine.search(query, limit=limit)
    assembler = PromptAssembler()
    return assembler.assemble(results, output_format=OutputFormat.LLMS_TXT)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Search the knowledge base.")
    parser.add_argument("query", help="Search query")
    parser.add_argument("--limit", "-l", type=int, default=10, help="Max results")
    args = parser.parse_args()

    print(search(args.query, limit=args.limit))
